default_language_version:
    python: python3.12
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
        - id: check-yaml
        - id: debug-statements
        - id: check-ast
        - id: check-executables-have-shebangs
        - id: check-shebang-scripts-are-executable
        - id: check-merge-conflict
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: fix-encoding-pragma
          args: [--remove]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.9
  hooks:
    - id: ruff
      exclude: ^tests/
      additional_dependencies:
        - ruff-lsp
      files: ^desktopstt/
      args: ["--fix"]
    - id: ruff-format
      exclude: ^tests/
      files: ^desktopstt/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        exclude: ^tests/
        args: [--ignore-missing-imports]
        additional_dependencies:
          - numpy
          - types-pyaudio
          - types-pyyaml

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
    -   id: shellcheck
        files: ^.*\.sh$
        args: ["--severity=warning", "--exclude=SC1091,SC2094,SC2129,SC2028"]
